Sculpture done
JohnnyZaev/JamGDTV2023 pull request #23
Opened 2023-05-25 17:42 UTC by Ferundal

Check line separators please.

2023-05-25 19:21 UTC, JohnnyZaev requested changes
Перемести еще пожалуйста скрипт скульптуры в папку Gameplay и добавь ей соответствующий неймспейс

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Editor/Drawers/ShowOnlyDrawer.cs
> +{
Класс не лежит в неймспейте Editor.Drawers

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +using UnityEngine.Serialization;
Serialization - неиспользуемый неймспейс

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +public class Sculpture : MonoBehaviour, IPointerClickHandler
Скульптура должна быть интерактабл обджект. Она будет содержать общие черты с остальными. Там в дальнейшем появится кол-во раз, которое можно кликнуть на объект и что с ним будет происходить после клика.

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +    }
Грубое нарушение инкапсуляции. Каждый может вытащить эту структуру и делать с ней все, что захочет

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +    [SerializeField] private List<SculptureStage> sculptureStages;
Почему был выбран лист? У нас есть четкое кол-во стадий и мы не будем добавлять их прямо во время игры. Превращаем мотание по структуре с O(1) в O(n) без какой-либо на причины

2023-05-25 19:21 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +    private int currentStage;
Атрибуты пляшу. Они у тебя то вверху переменной, то слева от нее. В проекте везде слева. Думаю стоит выбрать общий стиль. Ну или хоть 1 в пределах одного скрипта

2023-05-25 19:29 UTC, Ferundal commented on Assets/Editor/Drawers/ShowOnlyDrawer.cs
> +{
Его нельзя вносить в отдельный неймспейс, иначе нормально не работают ассеты со своими папками Editor

2023-05-25 19:31 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +public class Sculpture : MonoBehaviour, IPointerClickHandler
У скульптуры нет общих черт с остальными объектами кроме того, что она нажимаема, нет смысла наследовать абстракцию.

2023-05-25 19:32 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +    }
Это объявление структуры а не публичная структура.

2023-05-25 19:34 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +    [SerializeField] private List<SculptureStage> sculptureStages;
Согласен, лист не нужен.

2023-05-25 19:38 UTC, JohnnyZaev commented on Assets/Editor/Drawers/ShowOnlyDrawer.cs
> +{
Я свой эдитор код внес и все работает.

2023-05-25 19:40 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +public class Sculpture : MonoBehaviour, IPointerClickHandler
Как это нет? Она нажимаема, на нее можно кликнуть какое-то кол-во раз. Она что-то делает при нажатии и самое главное - она такой же интерактабл объект как и остальные. Сам абстрактный скрипт еще не до конца доработан, но я вижу ее как яркий пример интерактаблОбджекта. Объясни чем она отличается?

2023-05-25 19:41 UTC, JohnnyZaev commented on Assets/Scripts/Sculpture.cs
> +    }
Ну так зачем другим объектам такая структура? Если ты сделал ее для себя внутри скрипта

2023-05-25 19:53 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +    private int currentStage;
Ну я обычно так считаю если атрибут один и переменная короткая то можно в линию. Если атррибутов больше одного то лучше не в линию.

2023-05-25 19:55 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +    [SerializeField] private List<SculptureStage> sculptureStages;
Хотя нет, чекнул, разницы нет.

2023-05-25 20:30 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +    }
Я думал она не будет в эдиторе отображаться если честно. Но я чекнул отображается

2023-05-25 20:34 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +public class Sculpture : MonoBehaviour, IPointerClickHandler
Абстрактный метод делают если есть немаленькая общая часть с общим кодом. Если общая часть - унаследованный от интерфейса абстрактный метод - то в этом нет смысла.

2023-05-25 20:55 UTC, Ferundal commented on Assets/Scripts/Sculpture.cs
> +using UnityEngine.Serialization;
Справедливо.

2023-05-25 20:56 UTC, Ferundal commented on Assets/Editor/Drawers/ShowOnlyDrawer.cs
> +{
Не, бывает в ассетах свои отдельные папки "Editor" с ними конфликтует.

2023-05-26 08:41 UTC, JohnnyZaev approved these changes

2023-05-26 08:41 UTC, merged